server:
  port: 8002

mybatis:
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/imooc/miaosha/dao/*.xml

spring:
   application:
    name: config-miaosha-provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/miaosha              # 数据库名称
    username: root
    password: mysqladmin
    dbcp2:
      min-idle: 50                                           # 数据库连接池的最小维持连接数
      initial-size: 50                                      # 初始化连接数
      max-total: 50                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
redis:
  host: localhost
  port: 6379
  timeout: 3
  poolMaxTotal: 100
  poolMaxIdle: 100
  poolMaxWait: 3

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: parking-8002.com
    prefer-ip-address: true

info:
  app.name: config-eureka-provider
  company.name: xiaoxiaoqiang